// src/constants/genres.ts
export const GENRE_KEYS = [
    "action",
    "adventure",
    "animeSeriesInternationalTVShows",
    "britishTVShowsDocuseriesInternationalTVShows",
    "children",
    "comedies",
    "comediesDramasInternationalMovies",
    "comediesInternationalMovies",
    "comediesRomanticMovies",
    "crimeTVShowsDocuseries",
    "documentaries",
    "documentariesInternationalMovies",
    "docuseries",
    "dramas",
    "dramasInternationalMovies",
    "dramasRomanticMovies",
    "familyMovies",
    "fantasy",
    "horrorMovies",
    "internationalMoviesThrillers",
    "internationalTVShowsRomanticTVShowsTVDramas",
    "kidsTV",
    "languageTVShows",
    "musicals",
    "natureTV",
    "realityTV",
    "spirituality",
    "tvAction",
    "tvComedies",
    "tvDramas",
    "talkShowsTVComedies",
    "thrillers"
  ];
  
  export const GENRE_LABELS: Record<string, string> = {
    action: "Action",
    adventure: "Adventure",
    animeSeriesInternationalTVShows: "Anime & International TV",
    britishTVShowsDocuseriesInternationalTVShows: "British & International Docuseries",
    children: "Children",
    comedies: "Comedies",
    comediesDramasInternationalMovies: "Comedy-Drama (International)",
    comediesInternationalMovies: "International Comedies",
    comediesRomanticMovies: "Romantic Comedies",
    crimeTVShowsDocuseries: "Crime Docuseries",
    documentaries: "Documentaries",
    documentariesInternationalMovies: "International Documentaries",
    docuseries: "Docuseries",
    dramas: "Dramas",
    dramasInternationalMovies: "International Dramas",
    dramasRomanticMovies: "Romantic Dramas",
    familyMovies: "Family Movies",
    fantasy: "Fantasy",
    horrorMovies: "Horror",
    internationalMoviesThrillers: "International Thrillers",
    internationalTVShowsRomanticTVShowsTVDramas: "Romantic International TV",
    kidsTV: "Kids TV",
    languageTVShows: "Foreign Language TV",
    musicals: "Musicals",
    natureTV: "Nature TV",
    realityTV: "Reality TV",
    spirituality: "Spirituality",
    tvAction: "TV Action",
    tvComedies: "TV Comedies",
    tvDramas: "TV Dramas",
    talkShowsTVComedies: "Talk Shows & Comedies",
    thrillers: "Thrillers"
  };
  